on: 
  push:
jobs:

  build:

    runs-on: windows-2022
    timeout-minutes: 20
      
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3
        
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Update AppxPackage.Targets
        run: (Get-Content "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Msbuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppxPackage.Targets").Replace(')_Test\', ')\') | Set-Content "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Msbuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppxPackage.Targets"

      - name: Print AppxPackage.Targets
        run: more "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Msbuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppxPackage.Targets"
