on:
  push:
    branches: [ACS_Test]

jobs:
  sign:
    runs-on: windows-2019
    name: Sign install files with Trusted Signing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sign files with Trusted Signing
        uses: azure/trusted-signing-action@v0.3.15
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://eus.codesigning.azure.net/
          code-signing-account-name: CADInnovations
          certificate-profile-name: CADInnovations-Profile
          files-folder: ${{ github.workspace }}
          files-folder-filter: msi
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

  pre-release:

    needs: sign
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Download the artifacts folder
        uses: actions/download-artifact@v3
        with:
          name: msi-installer-file-v${{ env.VersionNumber }}
      
      - name: Release the version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GIT_API_TOKEN }}"
          automatic_release_tag: "v${{ env.VersionNumber }}"
          title: "Beta v${{ env.VersionNumber }}"
          prerelease: true
          files: |
            *.msi
