on: 
  push:

jobs:

  build:

    runs-on: windows-2022
    timeout-minutes: 20
      
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3
        
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Setup dotnet-guid
        run: dotnet tool install -g dotnet-guid

      - name: DisableOutOfProcBuild 
        run: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\VSI\\DisableOutOfProcBuild\\DisableOutOfProcBuild.exe"

