on: 
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: List the tree structure before upload
        run: ls -R
       
    # Decode the base 64 encoded pfx and save the Signing_Certificate
      - name: Decode the pfx
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.PFX_CERTIFICATE }}")
          [IO.File]::WriteAllBytes("GitHubActionsWorkflow.pfx", $pfx_cert_byte)
 
      - name: sign the MSI
        run: signtool.exe sign /f GitHubActionsWorkflow.pfx /p "${{ secrets.PFX_CERTIFICATE }}" /fd SHA256 /td SHA256 /tr http://timestamp.url.com VersaNote-v1.10.0.msi

      # Remove the .pfx
      - name: Remove the .pfx
        run: Remove-Item -path GitHubActionsWorkflow.pfx
