on: 
  push:

jobs:

  release:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    
    steps:

      - name: Download the release notes file
        run: curl -o existing_VersaNote-Beta_Release_Notes.txt https://cadinnovations.ca/${{ vars.BETA_RELEASE_NOTES_URL }}

      - name: Create file for new release notes
        run: echo -e "Beta v${{ env.VersionNumber }}\n" > new_VersaNote-Beta_Release_Notes.txt

      - name: Merge release notes
        run: cat new_VersaNote-Beta_Release_Notes.txt existing_VersaNote-Beta_Release_Notes.txt > VersaNote-Beta_Release_Notes.txt

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Append text
        run: echo -e "Beta v${{ env.VersionNumber }}\n${{ steps.date.outputs.date }}" | cat - copy_VersaNote-Beta_Release_Notes.txt > VersaNote-Beta_Release_Notes.txt

      - name: list file contents
        run: cat VersaNote-Beta_Release_Notes.txt
