on: 
  push:

jobs:
  signtool:
    runs-on: windows-2022
  
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
             
    # Decode the base 64 encoded pfx and save the Signing_Certificate
      - name: Decode the pfx
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.PFX_CERTIFICATE }}")
          [IO.File]::WriteAllBytes("GitHubActionsWorkflow.pfx", $pfx_cert_byte)
 
      - name: sign the MSI
        run: signtool.exe sign /f GitHubActionsWorkflow.pfx /p "${{ secrets.PFX_PASSWORD }}" /fd SHA256 /td SHA256 /tr http://timestamp.digicert.com VersaNote-v1.10.0.msi

      # Remove the .pfx
      - name: Remove the .pfx
        run: Remove-Item -path GitHubActionsWorkflow.pfx

      - name: List the tree structure before upload
        run: ls -R

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: VersaNote-v1.10.0.msi
          path: Versa_Note\Versa_Note
          retention-days: 5
